### ISSUE TITLE
[ci] Fix failing travis build on debian 10

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#129]
The [travis build is failing on debian 10](https://travis-ci.org/openwisp/ansible-openwisp2/jobs/481321499) for some really weird reason:

```
TASK [Stouts.postfix : Install DKIM requirements (Debian)] *********************
/usr/bin/python: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by dwang** [comment]
It looks like this issue is related to [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911090) bug in Debian. 

@atb00ker did some testing and found out that the container needed to be upgraded, which makes sense, now that the bug is closed.

I applied the band-aid fix [here](https://github.com/openwisp/ansible-openwisp2/pull/120/files#diff-5b529e01c11b423d5e6d96ccf1feccdfR63), but it does not look like a viable solution. To fix it properly, I think the Dockerfile in [GitLab (ninuxorg/docker/ansible-debian)](https://gitlab.com/ninuxorg/docker/ansible-debian/blob/master/Dockerfile.debian10) should be updated.

Should I send a PR there?

**Comment by nemesisdesign** [comment]
@dwang @hispanico is this change fine?
https://gitlab.com/ninuxorg/docker/ansible-debian/merge_requests/4

**Comment by hispanico** [comment]
> @dwang @hispanico is this change fine?
> https://gitlab.com/ninuxorg/docker/ansible-debian/merge_requests/4

I've just accepted the merge request.

**Comment by dwang** [comment]
I think this issue can be closed now.
