### ISSUE TITLE
[install] Current release fails on some systems

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#68]
The current release fails on older systems (eg: ubuntu 14 LTS, debian 8), while it seems the latest commit fixes the issues but breaks installation on newer systems (ubuntu 16 LTS).

We need to solve this asap.

**Comment by UtkarshVerma** [comment]
Using your commit on the ansible galaxy role files fixed the issue for both, Ubuntu 14.04 and 16.04
openwisp/ansible-openwisp2@4cf5834

**Comment by UtkarshVerma** [comment]
I have currently made the changes to my forked repo:
github.com/UtkarshVerma/ansible-openwisp2

**Comment by UtkarshVerma** [comment]
I was able to run the current release without any errors on my VMs. They were, Ubuntu Server 14.04 and Ubuntu Server 16.04. 
The version of ansible which I installed was 2.4.2.0. Instead of using `ansible-galaxy install openwisp.openwisp2` I had used `ansible-galaxy install git+https//github.com/openwisp/ansible-openwisp2` to get the latest commits too.

**Comment by nemesisdesign** [comment]
Should be fixed.
